import type { Question, Sport, SportConfig } from "./types";

export const SPORT_CONFIGS: Record<Sport, SportConfig> = {
  football: {
    name: "Football",
    emoji: "🏈",
    color: "#0a3a5c",
    accent: "#0096E0",
  },
  basketball: {
    name: "Basketball",
    emoji: "🏀",
    color: "#7b2d00",
    accent: "#f97316",
  },
  soccer: {
    name: "Soccer",
    emoji: "⚽",
    color: "#0d3b6e",
    accent: "#38bdf8",
  },
  baseball: {
    name: "Baseball",
    emoji: "⚾",
    color: "#1e1b4b",
    accent: "#e11d48",
  },
};

export const QUESTIONS: Record<Sport, Question[]> = {
  football: [
    {
      id: 1,
      sport: "football",
      category: "Rules",
      question: "How many downs does an offense get to advance the ball 10 yards for a first down?",
      options: ["3 downs", "4 downs", "5 downs", "2 downs"],
      correct: 1,
      explanation: "In American football, the offense gets 4 downs to advance the ball 10 yards. If they succeed, they earn a new set of 4 downs. If they fail, possession transfers to the other team.",
      difficulty: "easy",
    },
    {
      id: 2,
      sport: "football",
      category: "Scoring",
      question: "How many points is a safety worth in American football?",
      options: ["1 point", "2 points", "3 points", "6 points"],
      correct: 1,
      explanation: "A safety is worth 2 points and is awarded to the defensive team when they tackle the ball carrier in their own end zone. After a safety, the scoring team also receives possession via a free kick.",
      difficulty: "medium",
    },
    {
      id: 3,
      sport: "football",
      category: "Rules",
      question: "What is the term for when the quarterback is tackled behind the line of scrimmage?",
      options: ["Fumble", "Interception", "Sack", "Blitz"],
      correct: 2,
      explanation: "A sack occurs when the quarterback is tackled behind the line of scrimmage while attempting to pass. It results in a loss of yards for the offense. The term was coined by NFL player Deacon Jones.",
      difficulty: "easy",
    },
    {
      id: 4,
      sport: "football",
      category: "Field",
      question: "How long is a standard NFL football field from end zone to end zone (including end zones)?",
      options: ["100 yards", "110 yards", "120 yards", "130 yards"],
      correct: 2,
      explanation: "An NFL field is 120 yards total — 100 yards of playing field plus two 10-yard end zones on each side. The field is also 53⅓ yards wide.",
      difficulty: "medium",
    },
    {
      id: 5,
      sport: "football",
      category: "Strategy",
      question: "What is a 'red zone' in football?",
      options: [
        "The area between the 50-yard line and the opponent's 40",
        "The final 20 yards before the opponent's end zone",
        "The area where penalties are reviewed",
        "The zone where only running plays are allowed",
      ],
      correct: 1,
      explanation: "The red zone refers to the area between the opponent's 20-yard line and their end zone. Offenses are considered in 'scoring position' here, and defenses tighten up significantly as field space shrinks.",
      difficulty: "medium",
    },
  ],
  basketball: [
    {
      id: 1,
      sport: "basketball",
      category: "Rules",
      question: "How long is the shot clock in the NBA?",
      options: ["20 seconds", "24 seconds", "28 seconds", "30 seconds"],
      correct: 1,
      explanation: "The NBA shot clock is 24 seconds. The offense must attempt a shot that hits the rim within 24 seconds of gaining possession, or possession transfers to the other team. The shot clock resets to 14 seconds after an offensive rebound.",
      difficulty: "easy",
    },
    {
      id: 2,
      sport: "basketball",
      category: "Scoring",
      question: "In the NBA, how far from the basket does the three-point line arc begin at its closest corners?",
      options: ["19 ft 9 in", "22 ft", "23 ft 9 in", "25 ft"],
      correct: 1,
      explanation: "The NBA three-point line is 22 feet from the basket in the corners and extends to 23 feet 9 inches at the top of the arc. This shorter corner three is a strategic shot used frequently in modern NBA play.",
      difficulty: "hard",
    },
    {
      id: 3,
      sport: "basketball",
      category: "Violations",
      question: "What is a 'double dribble' in basketball?",
      options: [
        "Dribbling with both hands simultaneously or restarting a dribble",
        "Dribbling for more than 10 seconds in the backcourt",
        "Taking more than 2 steps without dribbling",
        "Touching the ball while it's in the cylinder above the rim",
      ],
      correct: 0,
      explanation: "A double dribble violation occurs when a player dribbles with both hands at the same time, or stops dribbling and then starts dribbling again. The result is a turnover — the opposing team gets possession.",
      difficulty: "easy",
    },
    {
      id: 4,
      sport: "basketball",
      category: "Rules",
      question: "How many personal fouls does it take to foul out of an NBA game?",
      options: ["4 fouls", "5 fouls", "6 fouls", "7 fouls"],
      correct: 2,
      explanation: "In the NBA, a player fouls out after committing 6 personal fouls (or 2 technical fouls). In college basketball (NCAA) and FIBA, it's only 5 fouls. Once fouled out, the player cannot return.",
      difficulty: "easy",
    },
    {
      id: 5,
      sport: "basketball",
      category: "Strategy",
      question: "What offensive strategy involves a player setting a stationary screen for a teammate dribbling past, then rolling toward the basket?",
      options: ["Fast break", "Zone offense", "Pick and roll", "Isolation play"],
      correct: 2,
      explanation: "The pick and roll (also called screen and roll) is one of basketball's most fundamental offensive plays. Player A sets a pick (screen) for the ball handler, then rolls toward the basket. It forces the defense to make a split-second decision and creates mismatches.",
      difficulty: "medium",
    },
  ],
  soccer: [
    {
      id: 1,
      sport: "soccer",
      category: "Rules",
      question: "How long is a standard professional soccer match?",
      options: ["80 minutes", "90 minutes", "100 minutes", "120 minutes"],
      correct: 1,
      explanation: "A standard soccer match is 90 minutes, divided into two 45-minute halves. A referee adds 'stoppage time' at the end of each half to compensate for delays. If knockout matches are tied, they go to 30 minutes of extra time, then penalty kicks.",
      difficulty: "easy",
    },
    {
      id: 2,
      sport: "soccer",
      category: "Rules",
      question: "What is the offside rule in soccer?",
      options: [
        "A player cannot be behind the last defender when the ball is played to them",
        "A player cannot touch the ball twice in a row",
        "A goalkeeper cannot hold the ball for more than 6 seconds",
        "A player cannot enter the penalty box before a penalty kick",
      ],
      correct: 0,
      explanation: "A player is offside if they are in the opponent's half and closer to the opponent's goal line than both the ball and the second-to-last defender (usually the last outfield player) at the moment the ball is played to them. It prevents goal-hanging.",
      difficulty: "medium",
    },
    {
      id: 3,
      sport: "soccer",
      category: "Scoring",
      question: "What is the distance from the penalty spot to the goal line?",
      options: ["8 yards", "10 yards", "12 yards", "15 yards"],
      correct: 2,
      explanation: "The penalty spot is exactly 12 yards (11 meters) from the goal line. Penalty kicks are awarded for fouls committed inside the penalty box. Statistically, penalty kicks are scored about 75-80% of the time at elite levels.",
      difficulty: "medium",
    },
    {
      id: 4,
      sport: "soccer",
      category: "Field",
      question: "How many players from each team are on the field during a standard match?",
      options: ["9 players", "10 players", "11 players", "12 players"],
      correct: 2,
      explanation: "Each team fields 11 players, including the goalkeeper. If players are sent off with red cards and a team drops to fewer than 7 players, the match is typically abandoned. A standard formation lists 10 outfield players plus the goalkeeper.",
      difficulty: "easy",
    },
    {
      id: 5,
      sport: "soccer",
      category: "Strategy",
      question: "What does the term 'pressing' mean in modern soccer tactics?",
      options: [
        "Playing with a high defensive line",
        "Aggressively hunting the ball immediately after losing possession",
        "Using physical strength to dominate aerial duels",
        "Holding a deep defensive block to absorb pressure",
      ],
      correct: 1,
      explanation: "Pressing (or gegenpressing) refers to a team immediately and aggressively trying to win back the ball after losing it, rather than retreating to a defensive shape. Popularized by managers like Jürgen Klopp, it aims to win the ball high up the pitch when the opposition is disorganized.",
      difficulty: "hard",
    },
  ],
  baseball: [
    {
      id: 1,
      sport: "baseball",
      category: "Rules",
      question: "How many strikes does it take to strike out a batter?",
      options: ["2 strikes", "3 strikes", "4 strikes", "5 strikes"],
      correct: 1,
      explanation: "Three strikes result in a strikeout. A strike is recorded when the batter swings and misses, when a pitch passes through the strike zone without being swung at, or when a foul ball is hit with fewer than 2 strikes.",
      difficulty: "easy",
    },
    {
      id: 2,
      sport: "baseball",
      category: "Rules",
      question: "What is a 'force out' in baseball?",
      options: [
        "When a runner is tagged while not on a base",
        "When a fielder with the ball touches a base before the runner who is forced to advance",
        "When a batter is hit by a pitch",
        "When a fly ball is caught for an out",
      ],
      correct: 1,
      explanation: "A force out (or force play) occurs when a runner must advance because the batter became a runner. A fielder just needs to touch the base with possession of the ball — they don't need to tag the runner. Force outs enable double plays.",
      difficulty: "medium",
    },
    {
      id: 3,
      sport: "baseball",
      category: "Scoring",
      question: "What is a 'grand slam' in baseball?",
      options: [
        "A home run with no runners on base",
        "A home run with the bases loaded (3 runners on base)",
        "A hit that scores 3 runs",
        "A home run that wins the game in the final inning",
      ],
      correct: 1,
      explanation: "A grand slam is a home run hit with all three bases occupied (bases loaded), scoring 4 runs total — the maximum possible on a single play. It's one of the most exciting plays in baseball and immediately changes game momentum.",
      difficulty: "easy",
    },
    {
      id: 4,
      sport: "baseball",
      category: "Field",
      question: "How far is it from home plate to first base?",
      options: ["60 feet", "75 feet", "90 feet", "100 feet"],
      correct: 2,
      explanation: "The bases in Major League Baseball are exactly 90 feet apart, forming a square called the diamond. This distance was established in 1857 and is considered nearly perfect — close plays at first base happen constantly, keeping the game exciting.",
      difficulty: "medium",
    },
    {
      id: 5,
      sport: "baseball",
      category: "Pitching",
      question: "What is the 'strike zone' in baseball?",
      options: [
        "The area directly over home plate, between the batter's armpits and knees",
        "The area above home plate, between the batter's shoulders and ankles",
        "Any pitch within 6 inches of the plate",
        "The area above home plate, between the belt and the knees",
      ],
      correct: 0,
      explanation: "The official strike zone is the area over home plate between the midpoint of the batter's torso (roughly armpits) and the hollow beneath their kneecap. In practice, umpires call the zone slightly differently, and technology like MLB's Statcast tracks every pitch precisely.",
      difficulty: "medium",
    },
  ],
};
